"""updated is_vegatarian to is_vegetarian

Revision ID: fa221762c6d7
Revises: 
Create Date: 2026-06-17 13:22:16.558806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa221762c6d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vegetarian', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_vegatarian')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vegatarian', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_vegetarian')

    # ### end Alembic commands ###
